### ISSUE TITLE
Editor obtaining as plugin.

### ISSUE THREAD

**Issue by kozusznik** [fiji-hpc/scijava-parallel#30]
Provide JavaFX forms functionality as plugin - as are provided by legacy forms in branch 
https://github.com/fiji-hpc/scijava-parallel/tree/editorSettingsByDI

**Comment by velissarious** [comment]
I added new Editor plugins that implement RunnerSettingsEditor for the new JavaFX forms (LocalSettingsScreenWindow and HPCSettingsScreenWindow).

**Comment by kozusznik** [comment]
Changes merged integrated into master.
