### ISSUE TITLE
Discuss code convention

### ISSUE THREAD

**Issue by PetrBainar** [fiji-hpc/scijava-parallel#9]
Discuss and/or define code convention for the scijava-parallel project. Moreover, define an IDE preset which could be used by all applicable developers.

**Comment by imagejan** [comment]
FYI, you might want to stick to the common SciJava/ImageJ [coding style](https://imagej.net/Coding_style#Eclipse_code_style_profiles) profiles (i.e. the eclipse preferences [here](https://github.com/imagej/imagej/blob/master/config/eclipse-preferences.epf)).

**Comment by PetrBainar** [comment]
Hi @imagejan,

Many thanks for your input! We have downloaded the suggested Eclipse preferences file and immediately put it into use 👍 

Regards,
Petr
